version: '2.3'

services:
  tf:
    build: .
    runtime: nvidia
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - ./:/tf
